<a href="https://colab.research.google.com/github/KimRRRich/PytorchExercise/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.4.1+cu121'

scalar = torch.tensor(7)
scalar
print("scalar:",scalar)
print("scalar.ndim:",scalar.ndim)
print("scalar.shape:",scalar.shape)

In [6]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector
print("vector:",vector)
print("vector.ndim:",vector.ndim)
print("vector.shape:",vector.shape)

vector: tensor([7, 7])
vector.ndim: 1
vector.shape: torch.Size([2])


In [11]:
martix = torch.tensor([[7,8],
                      [9,10]])
martix
print("martix:",martix)
print("martix.ndim:",martix.ndim)
print("martix.shape:",martix.shape)

martix: tensor([[ 7,  8],
        [ 9, 10]])
martix.ndim: 2
martix.shape: torch.Size([2, 2])


In [13]:
Tensor1 = torch.tensor([[1,2,3],[3,6,9],[2,4,5]])
Tensor1
print("Tensor1:",Tensor1)
print("Tensor1.ndim:",Tensor1.ndim)
print("Tensor1.shape:",Tensor1.shape)

Tensor: tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
Tensor.ndim: 2
Tensor.shape: torch.Size([3, 3])


In [2]:
Tensor2 = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                      [[1,1,1],[2,2,2],[3,3,3]]])
Tensor2
print("Tensor2:",Tensor2)
print("Tensor2.ndim:",Tensor2.ndim)
print("Tensor2.shape:",Tensor2.shape)

Tensor2: tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])
Tensor2.ndim: 3
Tensor2.shape: torch.Size([2, 3, 3])


In [7]:
random_tensor = torch.rand(3,4)
random_tensor, random_tensor.dtype

(tensor([[0.8803, 0.9315, 0.3449, 0.1785],
         [0.0829, 0.7296, 0.6166, 0.4442],
         [0.8714, 0.6331, 0.4767, 0.7036]]),
 torch.float32)

In [6]:
image_size = (224,224,3)
random_image_size_tensor = torch.rand(image_size)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [8]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [10]:
zero_to_ten_range = torch.arange(start=0, end=10, step=1)
zero_to_ten_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])