<a href="https://colab.research.google.com/github/KimRRRich/PytorchExercise/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.4.1+cu121'

scalar = torch.tensor(7)
scalar
print("scalar:",scalar)
print("scalar.ndim:",scalar.ndim)
print("scalar.shape:",scalar.shape)

In [6]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector
print("vector:",vector)
print("vector.ndim:",vector.ndim)
print("vector.shape:",vector.shape)

vector: tensor([7, 7])
vector.ndim: 1
vector.shape: torch.Size([2])


In [11]:
martix = torch.tensor([[7,8],
                      [9,10]])
martix
print("martix:",martix)
print("martix.ndim:",martix.ndim)
print("martix.shape:",martix.shape)

martix: tensor([[ 7,  8],
        [ 9, 10]])
martix.ndim: 2
martix.shape: torch.Size([2, 2])


In [13]:
Tensor1 = torch.tensor([[1,2,3],[3,6,9],[2,4,5]])
Tensor1
print("Tensor1:",Tensor1)
print("Tensor1.ndim:",Tensor1.ndim)
print("Tensor1.shape:",Tensor1.shape)

Tensor: tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
Tensor.ndim: 2
Tensor.shape: torch.Size([3, 3])


In [2]:
Tensor2 = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                      [[1,1,1],[2,2,2],[3,3,3]]])
Tensor2
print("Tensor2:",Tensor2)
print("Tensor2.ndim:",Tensor2.ndim)
print("Tensor2.shape:",Tensor2.shape)

Tensor2: tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])
Tensor2.ndim: 3
Tensor2.shape: torch.Size([2, 3, 3])


In [7]:
random_tensor = torch.rand(3,4)
random_tensor, random_tensor.dtype

(tensor([[0.8803, 0.9315, 0.3449, 0.1785],
         [0.0829, 0.7296, 0.6166, 0.4442],
         [0.8714, 0.6331, 0.4767, 0.7036]]),
 torch.float32)

In [6]:
image_size = (224,224,3)
random_image_size_tensor = torch.rand(image_size)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [8]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [10]:
zero_to_ten_range = torch.arange(start=0, end=10, step=1)
zero_to_ten_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ten_zeros = torch.zeros_like(zero_to_ten_range)
ten_zeros

ten_ones = torch.ones_like(zero_to_ten_range)
ten_ones
print("ten_zeros:",ten_zeros)
print("ten_ones:",ten_ones)

ten_zeros: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
ten_ones: tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [14]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Device tensor is stored on:{some_tensor.device}")

tensor([[0.6522, 0.0447, 0.0066, 0.1116],
        [0.1877, 0.4420, 0.6889, 0.6805],
        [0.5887, 0.9779, 0.7879, 0.2639]])
Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu


In [24]:
tensor = torch.tensor([1,2,3])
tensor1 = torch.tensor([3,4,5])
print(f"tensor*tensor:{tensor*tensor}")
print(f"tensor*tensor1:{tensor*tensor1}")
tmp1 = torch.matmul(tensor,tensor)
print(f"tensor@tensor:{tmp}")
tmp2 = tensor@tensor1
print(f"tensor@tensor1:{tmp2}")

matrix1 = torch.tensor([[1,1,1],[2,2,2]])
matrix2 = torch.tensor([[3,3,3],[4,4,4]])
print(f"matrix1*matrix2:{matrix1*matrix2}")
print(f"matrix1@matrix2:{matrix1@matrix2.T}")

tensor*tensor:tensor([1, 4, 9])
tensor*tensor1:tensor([ 3,  8, 15])
tensor@tensor:14
tensor@tensor1:26
matrix1*matrix2:tensor([[3, 3, 3],
        [8, 8, 8]])
matrix1@matrix2:tensor([[ 9, 12],
        [18, 24]])


In [21]:
tensor1 = torch.tensor([[1.,2.],
                        [3.,4.],
                        [5.,6.]],dtype = torch.float32)

tensor2 =  torch.tensor([[7.,8.],
                         [9.,10.],
                         [11.,12.]],dtype = torch.float32)

torch.matmul(tensor1,tensor2.T)
print(f"tensor1.shape:{tensor1.shape}")
print(f"tensor2.shape:{tensor2.shape}")
print(f"tensor2.T.shape:{tensor2.T.shape}")
print(f"torch.transpose(tensor2,0,1):{torch.transpose(tensor2,0,1)}")

tensor1.shape:torch.Size([3, 2])
tensor2.shape:torch.Size([3, 2])
tensor2.T.shape:torch.Size([2, 3])
torch.transpose(tensor2,0,1):tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])


In [31]:
tensor_A = torch.tensor([[1.,2.,3.],
                        [3.,4.,4.],
                        [5.,6.,5.],
                         [7.,8.,6.]],dtype = torch.float32)
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=3,out_features=6)
x = tensor_A
output = linear(x)
print(f"input shape:{x.shape}\n")
print(f"output:\n{output}\n\noutput shape:{output.shape}")

input shape:torch.Size([4, 3])

output:
tensor([[0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476],
        [2.4305, 1.6983, 2.2828, 1.1012, 2.4715, 2.2601],
        [4.1364, 2.6225, 2.9078, 1.3658, 3.7594, 3.0725],
        [5.8424, 3.5467, 3.5327, 1.6304, 5.0472, 3.8850]],
       grad_fn=<AddmmBackward0>)

output shape:torch.Size([4, 6])


In [40]:
x = torch.arange(0,100,10)
print(f"x:{x}")
print(f"Min:{x.min()}")
print(f"Min:{torch.min(x)}")
print(f"Max:{x.max()}")
print(f"Max:{torch.max(x)}")
print(f"Mean:{x.type(torch.float32).mean()}")
print(f"Mean:{torch.mean(x.type(torch.float32))}")
print(f"Sum:{x.sum()}")
print(f"Sum:{torch.sum(x)}")

x:tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Min:0
Min:0
Max:90
Max:90
Mean:45.0
Mean:45.0
Sum:450
Sum:450


In [43]:
tensor = torch.arange(10,100,10)
print(f"tensor:{tensor}")
print(f"torch.argmin(tensor):{torch.argmin(tensor)}")
print(f"tensor.argmax(tensor):{torch.argmax(tensor)}")

tensor:tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.argmin(tensor):0
tensor.argmax(tensor):8


In [45]:
tensor = torch.arange(10.,100.,10.)
print(tensor.dtype)
tensor_16 = tensor.type(torch.float16)
print(tensor_16.dtype)
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8.dtype)

torch.float32
torch.float16
torch.int8


In [58]:
tensor = torch.arange(1.,9.)
print(tensor,tensor.shape)
tensor_reshaped = tensor.reshape(1,8)
print(tensor_reshaped,tensor_reshaped.shape)
tensor_view = tensor.view(1,8)
print(tensor_view,tensor_view.shape)
tensor_view[:,0] = 5
tensor_view[:,1] = 6
tensor_view[:,-1] = 0
tensor_view[:,-2] = 1
print(tensor,tensor.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]) torch.Size([1, 8])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]) torch.Size([1, 8])
tensor([5., 6., 3., 4., 5., 6., 1., 0.]) torch.Size([8])


In [67]:
tensor = torch.arange(1.,9.)
tensor1= torch.arange(9.,17.)
print(tensor,tensor.shape)
x_stacked1 = torch.stack([tensor, tensor, tensor1], dim=0)
print(x_stacked1,x_stacked1.shape)
x_stacked2 = torch.stack([tensor, tensor, tensor1], dim=1)
print(x_stacked,x_stacked.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13., 14., 15., 16.]]) torch.Size([3, 8])
tensor([[ 1.,  1.,  9.],
        [ 2.,  2., 10.],
        [ 3.,  3., 11.],
        [ 4.,  4., 12.],
        [ 5.,  5., 13.],
        [ 6.,  6., 14.],
        [ 7.,  7., 15.],
        [ 8.,  8., 16.]]) torch.Size([8, 3])


In [73]:
tensor = torch.arange(1.,9.)
print(tensor,tensor.shape)
tensor_reshaped = tensor.reshape(1,8)
print(tensor_reshaped,tensor_reshaped.shape)
x_squeezed = tensor.squeeze()
print(x_squeezed,x_squeezed.shape)
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed,x_unsqueezed.shape)
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed,x_unsqueezed.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]) torch.Size([1, 8])
tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]) torch.Size([1, 8])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]) torch.Size([8, 1])


In [80]:
x_original = torch.rand(224,225,3)
x_permuted = x_original.permute(2,0,1)
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 225, 3])
torch.Size([3, 224, 225])


In [99]:
x = torch.arange(1,10)
print(x,x.shape)
x_reshaped = x.reshape(1,3,3)
print(x_reshaped,x_reshaped.shape)

print(x_reshaped[0])
print(x_reshaped[0][0])
print(x_reshaped[0][0][0])
print(x_reshaped[0][1][1])

print(x_reshaped[:,0])
print(x_reshaped[:,-2:,2:])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(5)
tensor([[1, 2, 3]])
tensor([[[6],
         [9]]])


In [1]:
!nvidia-smi

Wed Sep 25 06:53:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [4]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Count number of devices
torch.cuda.device_count()

1

In [5]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [7]:
import torch
tensor = torch.rand(7,7)
print(tensor)
tensor2 = torch.rand(1,7)
print(tensor2)
tensor3 = torch.matmul(tensor,tensor2.T)
print(tensor3)

tensor([[0.8686, 0.3319, 0.3160, 0.5550, 0.9694, 0.9593, 0.5935],
        [0.1119, 0.4680, 0.3015, 0.5987, 0.5592, 0.3078, 0.5687],
        [0.4723, 0.4077, 0.2346, 0.9614, 0.0819, 0.9868, 0.7405],
        [0.7299, 0.7666, 0.7982, 0.5338, 0.0090, 0.8581, 0.9858],
        [0.6946, 0.6216, 0.2404, 0.7364, 0.9362, 0.9158, 0.4529],
        [0.2936, 0.4720, 0.2148, 0.7753, 0.3444, 0.0255, 0.7481],
        [0.7991, 0.5037, 0.9391, 0.1265, 0.9181, 0.4509, 0.2047]])
tensor([[0.3065, 0.4641, 0.8673, 0.5540, 0.0064, 0.6215, 0.5745]])
tensor([[1.9451],
        [1.3662],
        [2.1092],
        [2.6672],
        [1.9531],
        [1.3727],
        [1.7669]])


tensor(2)
tensor([[0.2662, 0.0109, 0.7976, 0.5887, 0.0794, 0.6951, 0.1958]])


RuntimeError: both arguments to matmul need to be at least 1D, but they are 0D and 2D